// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsb2uM5c7mB1u3UMNo9rGh3k8Frplg4qE',
    appId: '1:163952813467:web:1b112d7cfef03a770d2d3e',
    messagingSenderId: '163952813467',
    projectId: 'shoes-app-9667f',
    authDomain: 'shoes-app-9667f.firebaseapp.com',
    storageBucket: 'shoes-app-9667f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTL2YdUBxQF_8MdkCtLjBuuFVd94D9j1g',
    appId: '1:163952813467:android:1fbc17f668c211110d2d3e',
    messagingSenderId: '163952813467',
    projectId: 'shoes-app-9667f',
    storageBucket: 'shoes-app-9667f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEBc1AXNhYXfZvCBEDXSgepY90T3jrLko',
    appId: '1:163952813467:ios:cc69b7d03b064aa40d2d3e',
    messagingSenderId: '163952813467',
    projectId: 'shoes-app-9667f',
    storageBucket: 'shoes-app-9667f.appspot.com',
    iosClientId: '163952813467-rlkkt389dle3ah0dtkka2fa4pofvpsne.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesAppUiTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEBc1AXNhYXfZvCBEDXSgepY90T3jrLko',
    appId: '1:163952813467:ios:cc69b7d03b064aa40d2d3e',
    messagingSenderId: '163952813467',
    projectId: 'shoes-app-9667f',
    storageBucket: 'shoes-app-9667f.appspot.com',
    iosClientId: '163952813467-rlkkt389dle3ah0dtkka2fa4pofvpsne.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesAppUiTraining',
  );
}
